const AppConstants = {
  ROUTES: {
    BASE: '/',
    BLOG: '/blog',
    POST: '/post/:post',
    ARCHIVE: '/archive/:page?',
    PHYSICS: '/physics/:catagory?/:section?/:post?',
    PROJECTS: '/projects',
    MORE: '/more',
    SEARCH: '/search/:term?',
    ERROR: '/error',
    REDIRECTOR: '/:link+',
  },
  LINKS: {
    BASE: '/',
    BLOG: '/blog',
    POST: '/post',
    ARCHIVE: '/archive',
    PHYSICS: '/physics',
    PROJECTS: '/projects',
    MORE: '/more',
    SEARCH: '/search',
    ERROR: '/error',
  },
  Physics: {
    CATAGORIES: {
      QUANTUM: '/physics/quantum',
      THERMAL: '/physics/thermal',
      CLASSICAL: '/physics/classical',
      ELECTROMAG: '/physics/electromag',
      ASTRO: '/physics/astro',
      MATHS: '/physics/maths',
    },
  },
  SiteColor: '#FFCA1E',
  TwitterLink: 'https://twitter.com/dannywrayuk',
  InstagramLink: 'https://www.instagram.com/dannywrayuk/',
  LinkedInLink: 'https://www.linkedin.com/in/dannywrayuk/',
  SpotifyLink: 'https://open.spotify.com/user/sciencekidd97',
  GitHubLink: 'https://github.com/dannywrayuk',
  version: `v${process.env.REACT_APP_VERSION}`,
};
export default AppConstants;
