name: Build Infrastructure
on:
  workflow_dispatch:

jobs:
  build-infra:
    name: Build Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Get Function ETag
        run: echo "ETAG=$(aws cloudfront describe-function --name clean-url-handler --query ETag --output text)" >> $GITHUB_ENV

      - name: Update Cloudfront Function
        run: >
          aws cloudfront update-function
          --name clean-url-handler
          --function-code fileb://infrastructure/clean-url-handler.js
          --function-config Comment="Add file extensions when a clean URL is requested",Runtime=cloudfront-js-1.0
          --if-match ${{ env.ETAG }}

      - name: Update Function ETag
        run: echo "ETAG=$(aws cloudfront describe-function --name clean-url-handler --query ETag --output text)" >> $GITHUB_ENV

      - name: Test Cloudfront Function
        run: >
          aws cloudfront test-function
          --name clean-url-handler
          --if-match ${{ env.ETAG }}
          --event-object fileb://infrastructure/test-request.json

      - name: Publish Cloudfront Function
        run: >
          aws cloudfront publish-function
          --name clean-url-handler
          --if-match ${{ env.ETAG }}
