name: CI
on:
  push:
    branches: [rebrand]
    paths:
      - 'infrastructure/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update Cloudfront Function 
        run: aws cloudfront update-function \
              --name clean-url-handler \
              --function-code ./infrastructure/clean-url-handler.js \
              --if-match ${{ secrets.AWS_CLOUDFRONT_ID_DEV }}

      - name: Test Cloudfront Function
         run: aws cloudfront test-function \
                --name clean-url-handler \ 
                --if-match ${{ secrets.AWS_CLOUDFRONT_ID_DEV }} \
                --event-object ./infrastructure/test-request.json

      -name: Publish Cloudfront Function
        run: aws cloudfront publish-function \
              --name clean-url-handler \
              --if-match ${{ secrets.AWS_CLOUDFRONT_ID_DEV }}